---
version: 2.1

orbs:
  common: cloudesire/common@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0
  slack: circleci/slack@4.2.0

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  # Pipeline parameters
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond
      with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  add-pr-comment:
    docker:
      - image: cimg/base:2021.01
    resource_class: small
    parameters:
      comment:
        type: string
    steps:
      - common/github_pr_add_comment:
          comment: << parameters.comment >>
  notify-slack:
    docker:
      - image: cimg/base:2021.01
    resource_class: small
    steps:
      - slack/notify:
          channel: "dev"
          custom: |
            {
              "text": ":rocket: New version of `common orb` have been released",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":rocket: New version of `common orb` have been released"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "CircleCI Build"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Github PR"
                      },
                      "url": "${CIRCLE_PULL_REQUEST}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Orb page"
                      },
                      "url": "https://circleci.com/developer/orbs/orb/cloudesire/common"
                    }
                  ]
                }
              ]
            }
          event: pass

workflows:
  build-and-deploy:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      - bats/run:
          path: ./src/tests
          context: common-backend
      - orb-tools/publish-dev:
          orb-name: cloudesire/common
          context: orb-publish # A restricted context containing your private publishing credentials. Will only execute if approved by an authorized user.
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - notify-slack:
          requires:
            - orb-tools/publish-dev
          context: common-backend
      - add-pr-comment:
          context: common-backend
          comment: "New orb beta version published: \\`cloudesire/common@dev:${CIRCLE_SHA1:0:7}\\`"
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore:
                - master
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger_publish
          context: orb-publish
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only:
                - master

  # This `integration-test_deploy` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  publish:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: cloudesire/common
          context: orb-publish
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          filters:
            branches:
              only:
                - master
      - notify-slack:
          context: common-backend

