---
version: 2.1

orbs:
  # Replace this with your own!
  #common: cloudesire/common@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond
      with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"



workflows:
  test-pack:
    when:
      not:
        equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      - orb-tools/publish-dev:
          orb-name: cloudesire/common
          context: orb-publish # A restricted context containing your private publishing credentials. Will only execute if approved by an authorized user.
          requires:
            - orb-tools/lint
            - orb-tools/pack

  # This `integration-test_deploy` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  publish:
    when:
      equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: cloudesire/common
          context: orb-publish
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
